### ISSUE TITLE
Trida obrazku

### ISSUE THREAD

**Issue by ViktoriaAndr** [xjaroso/PROJEKT-Sluzby#1]
https://github.com/xjaroso/PROJEKT-Sluzby/blob/b6fdf119af2c18fb939fa0d816e4dc9dd1c4a29c/style.css#L122
Ahoj,
moc pekný úkol.
Pri obrázkoch s triedou  one, two, three, ..atď mi napadlo, či potrebuje každý obrázok zvlášť triedu a či by sa nedali nastylovať s nejakou zjednotenou triedou?
Kód je takto zbytočne dlhý.

**Comment by xjaroso** [comment]
Viki moc děkuji za kontrolu nejen tohoto úkolu, issue fixed.
